config/routes.rb
###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree. 
###

require_relative '../lib/app_status'

BeaconControl::Application.routes.draw do
  mount(
    AppStatus::Rack.new do |config|
      config.add_class AppStatus::DatabaseCheckRequest, name: :database_ok?
      config.add_class AppStatus::MigrationsCheckRequest, name: :migrations_ok?
    end => '/status'
  )

  require 'sidekiq/web'
  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :applications, except: [:show] do
    member do
      post :set_apns_sandbox_cert
      post :set_apns_production_cert
    end

    resources :activities, except: [:new] do
      collection do
        get '/:event_type/new', to: 'activities#new', as: :new
        delete :destroy
      end
    end
    resources :rpush_apps_application, only: [:destroy]
    resource :applications_zones
    resource :applications_beacons

    resources :extensions, only: [:index], id: /[A-Z0-9\.]+/i, path: 'add_ons' do
      member do
        put :activate
        put :deactivate
      end
    end
  end

  devise_for :admins, controllers: {
    registrations: 'admin/registrations',
    confirmations: 'admin/confirmations',
    passwords: 'admin/passwords',
    sessions: 'admin/sessions',
  }
  as :admin do
    put 'admins/confirmation' => 'admin/confirmations#update', as: 'update_admin_confirmation'
    unless AppConfig.registerable
      get 'admins/edit' => 'admin/registrations#edit', as: :edit_admin_registration
      put 'admins/update' => 'admin/registrations#update', as: :admin_registration
    end
  end

  resource :profile, only: [:update]

  resources :admins, except: [:show], path: 'users' do
    collection do
      delete :batch_delete
    end
  end if AppConfig.user_management

  resource :static_pages, path: '', only: [] do
    member do
      get :introduction, path: 'walkthrough/intro'
      get :add_beacon, path: 'walkthrough/add_beacon'
      get :link_beacon, path: 'walkthrough/link_beacon'
      get :create_action, path: 'walkthrough/create_action'
      get :customize_features, path: 'walkthrough/customize_features'
      get :glossary, path: 'walkthrough/glossary'
    end
  end

  resources :beacons, except: [:show] do
    collection do
      patch :batch_update
      delete :batch_delete
      get :search
    end
  end
  resources :beacons_search, only: [:index]
  resources :zones

  resource :map

  resources :extension_assignments, only: [:show, :edit, :update]

  resources :extensions_marketplace, only: [:index, :edit, :update], id: /[A-Z0-9\.]+/i, path: 'add_ons' do
    member do
      put :activate
      put :deactivate
    end
  end

  scope 'api/v1', scope: 'api' do
    use_doorkeeper do
      skip_controllers :applications, :authorized_applications
    end
  end

  namespace :api do
    namespace :v1 do
      resources :configurations, only: [:index]
      resources :events, only: [:create]
    end
  end

  scope 's2s_api/v1', scope: 's2s_api' do
    use_doorkeeper do
      skip_controllers :applications, :authorized_applications
    end
  end

  namespace :s2s_api do
    namespace :v1 do
      resource :registrations, only: [:create], path: 'admins'
      resources :vendors, only: :index

      resource :password, only: [:create, :update]

      resources :applications, only: [:index, :create, :update, :destroy] do
        resources :application_settings, only: [:index] do
          collection do
            put :update
          end
        end

        resources :extensions, only: [], id: /[A-Z0-9\.]+/i do
          member do
            put :activate
            put :deactivate
          end
        end

        resources :activities, only: [:index, :create, :update, :destroy]
      end

      resources :zone_colors, only: [:index]
      resources :zones, only: [:index, :create, :update, :destroy] do
        member do
          get :beacons
        end
      end

      resources :beacons, only: [:index, :create, :update, :destroy] do
        collection do
          delete :index, action: :batch_destroy
        end

        member do
          get :info

          match 'config' => 'beacon_configs#update', via: :put
          match 'config' => 'beacon_configs#show', via: :get
          match 'beacon_updated' => 'beacon_configs#confirm', via: :put
          put :sync
        end
      end

      scope :admin do
        resources :admins, path: 'users', only: [:index, :create, :update, :destroy] if AppConfig.user_management
      end
    end
  end

  namespace :mobile do
    resources :coupons, only: [:show] do
      get :barcode
    end
  end

  if AppConfig.landing_page_url
    unauthenticated do
      as :admin do
        root to: redirect(AppConfig.landing_page_url), as: :unauthenticated_root
      end
    end
  end

  root to: 'dashboard#index'
end

app/controllers/static_pages_controller.rb
###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree. 
###

class StaticPagesController < AdminController
  def walkthrough
  end

  def introduction
  end

  def add_beacon
  end

  def link_beacon
  end

  def create_action
  end

  def customize_features
  end

  def glossary
  end
end

app/views/static_pages/_footer.html.erb
 <footer id="static-pages-footer">
   <div class="row">

     <div class="col-md-8">
       <a class="logo" title="Up-next" href="http://up-next.com">Up-next</a>
     </div>

     <div class="social-links-wrapper">
       <p><%= 'Follow Us:' %></p>
       <ul class="social-links">
         <li><a href="https://facebook.com/BeaconControl" class="facebook">Facebook</a></li>
         <li><a href="https://github.com/upnext/BeaconCtrl" class="github">Github</a></li>
         <li><a href="https://twitter.com/BeaconCtrl" class="twitter">Twitter</a></li>
       </ul>
     </div>

   </div>
 </footer>

app/views/static_pages/_header.html.erb
<nav id="main-nav">
  <%= link_to t('app_name'), root_path, class: 'logo' %>
</nav>

<nav id="sub-nav">
  <div class="container">
    Beginners' Guide
  </div>
</nav>

app/views/static_pages/_sidebar.html.erb
<div id="sticky-anchor"></div>
<div id="sticky" class='walkthrough-sidebar'>
  <ul>
    <li><%= active_link_to raw(t('walkthrough.sidebar.intro')), '/walkthrough/intro' %></a></li>
    <li><%= active_link_to raw(t('walkthrough.sidebar.add_beacon')), '/walkthrough/add_beacon' %></a></li>
    <li><%= active_link_to raw(t('walkthrough.sidebar.link_beacon')), '/walkthrough/link_beacon' %></a></li>
    <li><%= active_link_to raw(t('walkthrough.sidebar.create_action')), '/walkthrough/create_action' %></a></li>
    <li><%= active_link_to raw(t('walkthrough.sidebar.customize_features')), '/walkthrough/customize_features' %></a></li>
    <li><%= active_link_to raw(t('walkthrough.sidebar.glossary')), '/walkthrough/glossary' %></a></li>
  </ul>
</div>
        

app/views/static_pages/add_beacon.html.erb
<div class="walkthrough">
  <%= render 'sidebar' %>

  <div class='content'>
    <div id="add_beacon">

      <div class="title"><%= t('walkthrough.add_beacon.title') %></div>
      <p><%= raw t('walkthrough.add_beacon.description') %></p>

      <div class="subtitle"><%= t('walkthrough.add_beacon.admin_panel') %></div>
      <ol>
        <li>
          <%= t('walkthrough.add_beacon.add_beacon') %>
          <%= image_tag('walktrough/dashboard.png') %>
        </li>
        <li>
          <%= raw t('walkthrough.add_beacon.fill_in_beacon_data') %>
          <%= image_tag('walktrough/beacon_new.png') %>
        </li>
        <li><%= t('walkthrough.add_beacon.bring_phone') %></li>
      </ol>

      <div class="subtitle"><%= t('walkthrough.add_beacon.mobile_app') %></div>
      <ol>
        <li>
          <%= t('walkthrough.add_beacon.add_beacon_mobile') %>
          <%= image_tag('walktrough/01-mobile.png', class: 'two-images margin-t40') %>
           <%= image_tag('walktrough/02-mobile.png', class: 'two-images') %>
        </li>
        <li><%= raw t('walkthrough.add_beacon.setup_trigger') %></li>
        <li><%= t('walkthrough.add_beacon.bring_phone') %></li>
      </ol>

      <div class="subtitle"><%= t('walkthrough.add_beacon.sth_wrong') %></div>
      <ol>
        <li><%= raw t('walkthrough.add_beacon.no_mobile_app', mobile_app_url: "https://itunes.apple.com/pl/app/beaconctrl/id1020666394?mt=8") %></li>
        <li><%= t('walkthrough.add_beacon.not_same_account') %></li>
        <li><%= t('walkthrough.add_beacon.wrong_mobile_settings') %></li>
        <li><%= t('walkthrough.add_beacon.uuid_mistake') %></li>
        <li><%= t('walkthrough.add_beacon.battery_dead') %></li>
        <li><%= t('walkthrough.add_beacon.broken_beacon') %></li>
        <li><%= t('walkthrough.add_beacon.no_idea_what_wrong') %></li>
      </ol>
    </div>
  </div>
</div>

app/views/static_pages/create_action.html.erb
<div class="walkthrough">
  <%= render 'sidebar' %>

  <div class='content'>
    <div>
      <div class="title"><%= t('walkthrough.create_action.title') %></div>
      <p><%= raw t('walkthrough.create_action.choose_app') %></p>
      <p><%= raw t('walkthrough.create_action.see_actions', type_of_action_url: "#{glossary_static_pages_path}#action_type" ) %></p>
      <p><%= raw t('walkthrough.create_action.configure_action', zone_url: "#{glossary_static_pages_path}#zones", trigger_url: "#{glossary_static_pages_path}#trigger") %></p>
    </div>
  </div>
</div>

app/views/static_pages/customize_features.html.erb
<div class="walkthrough">
  <%= render 'sidebar' %>

  <div class='content'>
    <div>
      <div class="title"><%= t('walkthrough.customize_features.title') %></div>
      <p><%= raw t('walkthrough.customize_features.description') %></p>
    </div>
  </div>
</div>

app/views/static_pages/glossary.html.erb
<div class="walkthrough">
  <%= render 'sidebar' %>

  <div class='content'>
    <div>
      <div class="title"><%= t('walkthrough.glossary.title') %></div>
      <p><%= raw t('walkthrough.glossary.beacon_description') %></p>
      <p><%= raw t('walkthrough.glossary.beacon_vendors') %></p>
      <p><%= raw t('walkthrough.glossary.how_to_setup_beacons', setup_beacon_url: add_beacon_static_pages_path) %></p>
      <br/>
      <p><%= raw t('walkthrough.glossary.beacon_range') %></p>
      <p>
        <%= raw t('walkthrough.glossary.beacon_distance') %>
        <ul>
          <li><%= raw t('walkthrough.glossary.almost_touching') %></li>
          <li><%= raw t('walkthrough.glossary.nearby') %></li>
          <li><%= raw t('walkthrough.glossary.in_sight') %></li>
        </ul>
      </p>
      <br/>
      <p id="zones"><%= raw t('walkthrough.glossary.zones') %></p>
      <p><%= raw t('walkthrough.glossary.create_zone', create_zone_url: link_beacon_static_pages_path) %></p>
      <br/>
      <p><%= raw t('walkthrough.glossary.action_description') %></p>
      <p id="action_type"><%= raw t('walkthrough.glossary.types_of_actions') %>
        <ul>
          <li><%= raw t('walkthrough.glossary.url_actions') %></li>
          <li><%= raw t('walkthrough.glossary.custom_actions') %></li>
          <li><%= raw t('walkthrough.glossary.coupons_actions') %></li>
        </ul>
      </p>
      <br/>
      <p id="trigger"><%= raw t('walkthrough.glossary.trigger') %></p>
      <p><%= raw t('walkthrough.glossary.beacon_broadcast') %></p>
      <p><%= raw t('walkthrough.glossary.choose_trigger') %></p>
      <p><%= raw t('walkthrough.glossary.how_to_create_action', create_action_url: create_action_static_pages_path) %></p>
      <br/>
      <p id="add_on"><%= raw t('walkthrough.glossary.add_on') %></p>
      <p><%= raw t('walkthrough.glossary.how_to_enable_add_on', enable_add_on_url: customize_features_static_pages_path) %></p>
        <ul>
          <li><%= raw t('walkthrough.glossary.dwell_time', trigger_definition_url: "#{glossary_static_pages_path}#trigger") %></li>
          <li><%= raw t('walkthrough.glossary.presence_add_on', developers_documentation_url: "#{AppConfig.landing_page_url}/dev/backend-docs/") %></li>
          <li>
            <p><%= raw t('walkthrough.glossary.kontakt_io_add_on') %></p>
            <p><%= raw t('walkthrough.glossary.kontakt_io_beacons') %></p>
          </li>
          <li><%= raw t('walkthrough.glossary.analytics_add_on') %></li>
        </ul>
    </div>
  </div>
</div>

app/views/static_pages/introduction.html.erb
<div class="walkthrough">
  <%= render 'sidebar' %>

  <div class='content'>
    <div id="intro" >
      <div class="title"><%= t('walkthrough.introduction.title') %></div>
        
      <p>
        <%= raw t('walkthrough.welcome.intro', github_url: '<a href=https://github.com/upnext/BeaconCtrl target=_blank> https://github.com/upnext/BeaconCtrl </a>') %>
      </p>

      <div class="subtitle"><%= t('walkthrough.introduction.add_beacon') %></div>
      <p>
        <%= t('walkthrough.beacons.body') %>
      </p>
      <%= image_tag('walktrough/beacon_new.png') %>

      <div class="subtitle"><%= t('walkthrough.introduction.zones') %></div>
      <p>
        <%= t('walkthrough.zones.body') %>
      </p>
      <%= image_tag('walktrough/zones.png') %>

      <div class="subtitle"><%= t('walkthrough.introduction.map') %></div>
      <p>
        <%= t('walkthrough.map.body') %>
      </p>
      <%= image_tag('walktrough/map.png') %>

      <div class="subtitle"><%= t('walkthrough.introduction.applications') %></div>
      <p>
        <%= t('walkthrough.applications.body') %>
      </p>
      <%= image_tag('walktrough/applications.png') %>

      <div class="subtitle"><%= t('walkthrough.introduction.add_ons') %></div>
      <p>
        <%= t('walkthrough.addons.body') %>
      </p>
      <%= image_tag('walktrough/extensions.png') %>
    </div>
</div>

app/views/static_pages/link_beacon.html.erb
<div class="walkthrough">
  <%= render 'sidebar' %>

  <div class='content'>
    <div>
      <div class="title"><%= t('walkthrough.link_beacon.title') %></div>
      <p><%= raw t('walkthrough.link_beacon.description', setup_action_url: create_action_static_pages_path) %></p>
    </div>
  </div>
</div>

app/views/static_pages/walkthrough.html.erb
<div class="walkthrough">

  <div class='content'>

    <div id="setup_custom_action">
      <div class="subtitle">Setup an action in the test app using the dwelltime (custom action)</div>

      <ol>
        <li>Open admin panel</li>
        <%= image_tag('walktrough/extensions.png') %>

        <li>Click add beacon</li>
        <%= image_tag('walktrough/extensions.png') %>
        <li>Write beacon name, UUID, major and minor data</li>
        <li>Mark checkbox `test this beacon`</li>
        <li>Choose trigger `almoust touching`</li>
        <li>Click `save beacon` button</li>
        <li>Open application `BeaconControl` on your ipad</li>
        <li>Close iPhone to beacon and wait for notication</li>
        <li>Close iPhone to beacon and wait for notication</li>
        <li>Close iPhone to beacon and wait for notication</li>
        <li>Close iPhone to beacon and wait for notication</li>
      </ol>
    </div>

    <div id="setup_coupon_action">
      <div class="subtitle">Setup an action in the test app (coupon action)</div>

      <ol>
        <li>Open admin panel</li>
        <%= image_tag('walktrough/extensions.png') %>

        <li>Click add beacon</li>
        <%= image_tag('walktrough/extensions.png') %>
        <li>Write beacon name, UUID, major and minor data</li>
        <li>Mark checkbox `test this beacon`</li>
        <li>Choose trigger `almoust touching`</li>
        <li>Click `save beacon` button</li>
        <li>Open application `BeaconControl` on your ipad</li>
        <li>Close iPhone to beacon and wait for notication</li>
        <li>Close iPhone to beacon and wait for notication</li>
        <li>Close iPhone to beacon and wait for notication</li>
        <li>Close iPhone to beacon and wait for notication</li>
      </ol>
    </div>
  </div>
</div>