config/routes.rb
###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree. 
###

require_relative '../lib/app_status'

BeaconControl::Application.routes.draw do
  mount(
    AppStatus::Rack.new do |config|
      config.add_class AppStatus::DatabaseCheckRequest, name: :database_ok?
      config.add_class AppStatus::MigrationsCheckRequest, name: :migrations_ok?
    end => '/status'
  )

  require 'sidekiq/web'
  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :applications, except: [:show] do
    member do
      post :set_apns_sandbox_cert
      post :set_apns_production_cert
    end

    resources :activities, except: [:new] do
      collection do
        get '/:event_type/new', to: 'activities#new', as: :new
        delete :destroy
      end
    end
    resources :rpush_apps_application, only: [:destroy]
    resource :applications_zones
    resource :applications_beacons

    resources :extensions, only: [:index], id: /[A-Z0-9\.]+/i, path: 'add_ons' do
      member do
        put :activate
        put :deactivate
      end
    end
  end

  devise_for :admins, controllers: {
    registrations: 'admin/registrations',
    confirmations: 'admin/confirmations',
    passwords: 'admin/passwords',
    sessions: 'admin/sessions',
  }
  as :admin do
    put 'admins/confirmation' => 'admin/confirmations#update', as: 'update_admin_confirmation'
    unless AppConfig.registerable
      get 'admins/edit' => 'admin/registrations#edit', as: :edit_admin_registration
      put 'admins/update' => 'admin/registrations#update', as: :admin_registration
    end
  end

  resource :profile, only: [:update]

  resources :admins, except: [:show], path: 'users' do
    collection do
      delete :batch_delete
    end
  end if AppConfig.user_management

  resource :static_pages, path: '', only: [] do
    member do
      get :introduction, path: 'walkthrough/intro'
      get :add_beacon, path: 'walkthrough/add_beacon'
      get :link_beacon, path: 'walkthrough/link_beacon'
      get :create_action, path: 'walkthrough/create_action'
      get :customize_features, path: 'walkthrough/customize_features'
      get :glossary, path: 'walkthrough/glossary'
    end
  end

  resources :beacons, except: [:show] do
    collection do
      patch :batch_update
      delete :batch_delete
      get :search
    end
  end
  resources :beacons_search, only: [:index]
  resources :zones

  resource :map

  resources :extension_assignments, only: [:show, :edit, :update]

  resources :extensions_marketplace, only: [:index, :edit, :update], id: /[A-Z0-9\.]+/i, path: 'add_ons' do
    member do
      put :activate
      put :deactivate
    end
  end

  scope 'api/v1', scope: 'api' do
    use_doorkeeper do
      skip_controllers :applications, :authorized_applications
    end
  end

  namespace :api do
    namespace :v1 do
      resources :configurations, only: [:index]
      resources :events, only: [:create]
    end
  end

  scope 's2s_api/v1', scope: 's2s_api' do
    use_doorkeeper do
      skip_controllers :applications, :authorized_applications
    end
  end

  namespace :s2s_api do
    namespace :v1 do
      resource :registrations, only: [:create], path: 'admins'
      resources :vendors, only: :index

      resource :password, only: [:create, :update]

      resources :applications, only: [:index, :create, :update, :destroy] do
        resources :application_settings, only: [:index] do
          collection do
            put :update
          end
        end

        resources :extensions, only: [], id: /[A-Z0-9\.]+/i do
          member do
            put :activate
            put :deactivate
          end
        end

        resources :activities, only: [:index, :create, :update, :destroy]
      end

      resources :zone_colors, only: [:index]
      resources :zones, only: [:index, :create, :update, :destroy] do
        member do
          get :beacons
        end
      end

      resources :beacons, only: [:index, :create, :update, :destroy] do
        collection do
          delete :index, action: :batch_destroy
        end

        member do
          get :info

          match 'config' => 'beacon_configs#update', via: :put
          match 'config' => 'beacon_configs#show', via: :get
          match 'beacon_updated' => 'beacon_configs#confirm', via: :put
          put :sync
        end
      end

      scope :admin do
        resources :admins, path: 'users', only: [:index, :create, :update, :destroy] if AppConfig.user_management
      end
    end
  end

  namespace :mobile do
    resources :coupons, only: [:show] do
      get :barcode
    end
  end

  if AppConfig.landing_page_url
    unauthenticated do
      as :admin do
        root to: redirect(AppConfig.landing_page_url), as: :unauthenticated_root
      end
    end
  end

  root to: 'dashboard#index'
end

app/models/application.rb
###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree. 
###

require 'rpush'

class Application < ActiveRecord::Base
  APNS_APP = 'Rpush::Client::ActiveRecord::Apns::App'
  GCM_APP  = 'Rpush::Client::ActiveRecord::Gcm::App'

  belongs_to :account

  has_many :triggers
  has_many :activities, through: :triggers
  has_many :beacons, through: :account
  has_many :zones,   through: :account

  has_many :application_extensions

  has_many :application_settings, dependent: :destroy

  # Private
  has_many :rpush_apps, class_name: 'Rpush::Client::ActiveRecord::App'

  has_one :apns_app_production, ->{ where(rpush_apps: { environment: 'production' }) }, class_name: APNS_APP
  has_one :apns_app_sandbox,    ->{ where(rpush_apps: { environment: 'sandbox' }) },    class_name: APNS_APP
  has_one :gcm_app,             class_name: GCM_APP

  has_many :users
  has_many :mobile_devices, through: :users

  has_one :doorkeeper_application,
    class_name: 'Doorkeeper::Application',
    as: :owner

  accepts_nested_attributes_for :apns_app_production
  accepts_nested_attributes_for :apns_app_sandbox
  accepts_nested_attributes_for :gcm_app
  accepts_nested_attributes_for :application_settings

  validates :name, presence: true, uniqueness: { scope: :account }

  delegate :uid, :secret, to: :doorkeeper_application

  before_destroy :check_if_test_app

  def rpush_app_for_device(mobile_device)
    Application::PushApp.new(self, mobile_device).find
  end

  def active_extensions
    ExtensionsRegistry.active_extensions_for(application_extensions)
  end

  def inactive_extensions
    ExtensionsRegistry.inactive_extensions_for(application_extensions)
  end

  def activate_extension(extension)
    application_extensions.where(extension_name: extension.to_s).first_or_create
  end

  def deactivate_extension(extension)
    application_extensions.where(extension_name: extension.to_s).delete_all
  end

  def extension_active?(extension)
    application_extensions.where(extension_name: extension.to_s).exists?
  end

  def extension_by_name(extension)
    application_extensions.find_by(extension_name: extension.to_s)
  end

  private

  def check_if_test_app
    !self.test
  end
end

app/models/application/push_app.rb
###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree. 
###

class Application
  class PushApp
    delegate :os, :environment, to: :mobile_device

    def initialize(application, mobile_device)
      self.application   = application
      self.mobile_device = mobile_device
    end

    def find
      case os
      when 'ios'     then ios_app
      when 'android' then android_app
      end
    end

    private

    def ios_app
      case environment
      when 'production' then application.apns_app_production
      when 'sandbox'    then application.apns_app_sandbox
      end
    end

    def android_app
      application.gcm_app
    end

    attr_accessor :application, :mobile_device
  end
end

app/controllers/application_controller.rb
###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree.
###

class ApplicationController < ActionController::Base
  force_ssl if: -> { AppConfig.force_ssl }
  before_action :set_application_url


  def current_ability
    @current_ability ||= Ability.new(current_admin)
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: exception.message
  end

  def set_application_url
    if ActionMailer::Base.default_url_options[:host] != request.host
      ActionMailer::Base.default_url_options[:host] = AppConfig.mailer_url_options[:host] = request.host
    end
  end
end

app/controllers/applications_controller.rb
###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree. 
###

class ApplicationsController < AdminController
  inherit_resources
  load_and_authorize_resource

  before_action :build_rpush_apps, only: [
    :edit, :set_apns_production_cert, :set_apns_sandbox_cert
  ]
  before_action :build_app_settings, only: [
    :edit
  ]

  def create
    application = Application::Factory.new(current_admin, permitted_params)

    app = application.create
    if app.persisted?
      redirect_to application_activities_path(app)
    else
      redirect_to :back
    end
  end

  def update
    @application.update_attributes(permitted_params)

    redirect_to :back
  end

  def destroy
    @application.destroy
    redirect_to :back
  end

  def set_apns_sandbox_cert
    rpush_app = RpushApnsApp.new(
      cert_permitted_params[:apns_app_sandbox_attributes].merge(
        environment: 'sandbox',
        application: @application
      )
    ).app

    if rpush_app.valid?
      @application.apns_app_sandbox = rpush_app
      @application.save
    end

    redirect_to edit_application_path(@application)
  end

  def set_apns_production_cert
    rpush_app = RpushApnsApp.new(
      cert_permitted_params[:apns_app_production_attributes].merge(
        environment: 'production',
        application: @application
      )
    ).app

    if rpush_app.valid?
      @application.apns_app_production = rpush_app
      @application.save
    end

    redirect_to edit_application_path(@application)
  end

  private

  def permitted_params
    params.require(:application).permit(
      *test_app_permitted_params,
      application_settings_attributes: [:id, :extension_name, :type, :key, :value]
    )
  end

  def test_app_permitted_params
    application.test ? [] : [:name]
  end

  def cert_permitted_params
    params.require(:application).permit(
      apns_app_sandbox_attributes: [:id, :passphrase, :cert_p12],
      apns_app_production_attributes: [:id, :passphrase, :cert_p12]
    )
  end

  def begin_of_association_chain
    current_admin
  end

  def resource
    super.decorate
  end

  def collection
    @applications = super.decorate
  end

  def application
    @application ||= Application.new
  end
  helper_method :application

  def build_rpush_apps
    @application.apns_app_sandbox    || @application.build_apns_app_sandbox
    @application.apns_app_production || @application.build_apns_app_production
  end

  def build_app_settings
    ApplicationSetting::Factory.new(@application).build
  end
end

app/controllers/s2s_api/v1/applications_controller.rb
###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree. 
###

module S2sApi
  module V1
    class ApplicationsController < BaseController
      inherit_resources
      load_and_authorize_resource

      self.responder = S2sApiResponder

      actions :index, :update, :destroy

      def create
        factory = Application::Factory.new(current_admin, permitted_params[:application])
        resource = factory.create

        respond_with(resource)
      end

      private

      def begin_of_association_chain
        current_admin.account
      end

      def collection
        super.includes(:doorkeeper_application)
      end

      def permitted_params
        {
          application: params.fetch(:application, {}).permit(*test_app_permitted_params)
        }
      end

      def test_app_permitted_params
        (request.put? || request.patch?) && resource.test ? [] : [:name]
      end
    end
  end
end

app/helpers/application_helper.rb
###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree. 
###

module ApplicationHelper

  #
  # Pick the correct arguments for form_for when shallow routes are used.
  #
  # ==== Parameters
  #
  # * +parent+ - The Resource that has_* child
  # * +child+  - The Resource that belongs_to parent
  #
  def shallow_args(parent, child)
    child.try(:new_record?) ? [parent, child] : child
  end

  def glyphicon(name, text = nil)
    if text.present?
      "<span class=\"glyphicon glyphicon-#{name}\"></span> #{text}"
    else
      "<span class=\"glyphicon glyphicon-#{name}\"></span>"
    end.html_safe
  end

  def svg_tag(path, options = {})
    content_tag(:object, '', { data: path, type: 'image/svg+xml' }.merge(options)).html_safe
  end

  def link_to_modal(name, url, target, html_options = {})
    name = raw '<span class="bos bos-cancel"></span>' if name == :cancel_icon
    name = raw '<span class="bos bos-trash"></span>' if name == :trash_icon
    html_options[:class] = [*html_options[:class], 'with-modal'].join(' ')
    html_options.delete(:method)
    html_options[:data] ||= {}
    html_options[:data].merge! url: url, target: target

    link_to(name, target, html_options)
  end

  # @param [Symbol] action
  # @param [String] path
  # @param [Hash] opts
  # @return {String}
  def button_link(action, path, opts={})
    opts = opts.with_indifferent_access
    opts[:class] = *opts[:class]
    opts[:class] << 'btn-default' unless opts[:class].any? { |s| s.match(/btn\-.+/) }
    opts[:class] += button_class(action: action, static: !opts.delete(:dynamic_width))
    opts[:class].uniq!

    i18n = opts.delete(:i18n) || 'helpers.links'
    name = if t("#{ i18n }.#{action}", default: '').empty?
             t(".#{action}")
           else
             t(".#{action}", default: t("#{ i18n }.#{action}"))
           end
    if opts.delete(:with_modal)
      opts.delete(:method)
      opts[:data] ||= {}
      opts[:data].merge!(url: path)
      opts[:data][:target] ||= '#destroy-modal'
      link_to_modal(name, path, '#destroy-modal', opts)
    else
      link_to(name, path, opts)
    end
  end

  def button_class(*args, action:, static: false)
    %W[ btn btn-action-#{action}].push(static ? 'btn-static-width' : '').concat(args).uniq
  end

  #
  # Creates link to current path, with sorting parameters appended, i.e.
  # ?direction=desc&sort=name
  #
  def sortable(column, title = nil)
    title ||= column.titleize
    sorted_column = params.fetch(:sorted, {})[:column]
    sorted_direction = params.fetch(:sorted, {})[:direction]

    css_class = (column == sorted_column) ? "current #{sorted_direction}" : nil
    direction = (column == sorted_column && sorted_direction == "asc") ? "desc" : "asc"

    link_to title, params.merge(sorted: { column: column, direction: direction}), class: css_class
  end

  def walkthrough_data(index, part)
    {
      walkthrough_index:     index,
      walkthrough_highlight: index,
      walkthrough_title:     t("walkthrough.#{part}.title"),
      walkthrough_body:      t("walkthrough.#{part}.body")
    }
  end

  def logo_link_url
    AppConfig.landing_page_url || root_path
  end

  def edit?
    params[:action] == 'edit'
  end

  def new?
    params[:action] == 'new'
  end

  def current_beacon_zone_color
    return 'transparent' unless @beacon
    "##{@beacon.zone.try(:color) || BeaconFilterForm::UNASSIGNED_ZONE.color}"
  end
end

app/views/applications/_apns_cert_form.html.erb
<%= simple_nested_form_for @application, url: set_apns_sandbox_cert_application_path, method: :post do |f| %>
  <h3>APNS Sandbox</h3> <%= "(uploaded)" if @application.apns_app_sandbox.try(:persisted?) %>

  <%= f.simple_fields_for :apns_app_sandbox do |rpush_apps_application| %>
    <%= rpush_apps_application.input :passphrase, as: :password, placeholder: "Passphrase" %>
    <%= rpush_apps_application.input :cert_p12, as: :file %>
    <div class="form-group clearfix">
      <%= f.button :submit, t('.save'),
                   class: button_class('pull-right', action: :save, static: true)
      %>
      <% if rpush_apps_application.object.persisted? %>
        <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                    application_rpush_apps_application_path(@application, rpush_apps_application.object),
                    class: button_class('pull-right', action: :cancel, static: true),
                    method: :delete
        %>
      <% end %>
    </div>
  <% end %>
<% end %>

<%= simple_nested_form_for @application, url: set_apns_production_cert_application_path, method: :post do |f| %>
  <h3>APNS Production</h3> <%= "(uploaded)" if @application.apns_app_production.try(:persisted?) %>

  <%= f.simple_fields_for :apns_app_production do |rpush_apps_application| %>
    <%= rpush_apps_application.input :passphrase, as: :password, placeholder: "Passphrase" %>
    <%= rpush_apps_application.input :cert_p12, as: :file %>
    <div class="form-group clearfix">
      <%= f.button :submit, t('.save'),
                   class: button_class('pull-right', action: :save, static: true)
      %>
      <% if rpush_apps_application.object.persisted? %>
        <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                    application_rpush_apps_application_path(@application, rpush_apps_application.object),
                    class: button_class('pull-right', action: :cancel, static: true),
                    method: :delete
        %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/applications/_application.html.erb
<%###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree. 
###%>

<div class="controls">
  <%= link_to_modal(:cancel_icon, application_path(application), '#destroy-modal') unless application.test? %>
</div>
<%= link_to application_activities_path(application), class: %W[item-box edit] do %>
  <h3><%= application.name %></h3>
<% end %>

app/views/applications/_form.html.erb
<%###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree. 
###%>

<div class="row form-container">
  <div class="col-md-6 first-column">
    <%= simple_form_for @application do |f| %>
      <h3> Main </h3>

      <%= f.input :name, required: false %>

      <%= f.input :uid,    readonly: true %>
      <%= f.input :secret, readonly: true %>

      <div class="form-group clearfix">
        <%= f.button :submit, t('.save'),
                     class: button_class('pull-right', action: :save, static: true)
        %>
      </div>
    <% end %>

    <% @application.active_extensions.select{ |ext| ext.settings.present? }.each do |ext| %>
      <div id="<%= ext.extension_class.name.demodulize %>">
        <h3><%= ext.name %></h3>
        <%= simple_nested_form_for @application do |f| %>
          <% @application.application_settings.select{|s| s.extension_name == ext.name}.each do |app_setting| %>
            <%= f.simple_fields_for :application_settings, app_setting do |ff| %>
              <%= ff.input :extension_name, as: :hidden %>
              <%= ff.input :type, as: :hidden, input_html: {value: app_setting.read_attribute(:type)} %>
              <%= ff.input :key, as: :hidden %>
              <%= ff.input :value, as: app_setting.config[:type], label: t(app_setting.config[:i18n_key]) %>
              <% if app_setting.file? && app_setting.value.present? %>
                <%= link_to app_setting.value.file.filename, app_setting.value.url, target: :_blank %>
              <% end %>
            <% end %>
          <% end %>

          <div class="form-group clearfix">
            <%= f.button :submit, t('.save'),
                class: button_class('pull-right', action: :save, static: true)
            %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="col-md-6 second-column">
    <%= render 'apns_cert_form' unless @application.test? %>
  </div>

</div>

app/views/applications/_new.html.erb
<%###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree. 
###%>

<%= simple_form_for(application, html: { class: %W[header-action navbar-form navbar-right] }, wrapper: :simple_with_errors) do |f| %>
  <div class="form-group">
    <%= f.input :name, placeholder: t('.form_placeholder'), class: %W[form-control], required: true %>
  </div>
  <%= f.button :submit, t('.add_new'), class: %W[btn btn-sm btn-success hidden-xs] %>
  <%= f.button :submit, t('.add_new'), class: %W[btn btn-sm btn-success btn-block visible-xs] %>
<% end %>

app/views/applications/edit.html.erb
<%###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree. 
###%>

<% content_for :header_breadcrumbs do %>
  <span><%= link_to t('.title'), applications_path %></span>
  <span><%= @application.name %></span>
<% end %>

<%= render partial: 'shared/subheader' %>

<%= render partial: 'form' %>

app/views/applications/index.html.erb
<%###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree. 
###%>

<% content_for :header_breadcrumbs do %>
  <span><%= t('.title') %></span>
<% end %>

<ul class="items-list">
  <% @applications.each do |application| %>
    <li class="col-lg-4 col-md-6 col-xs-12">
      <%= render application %>
    </li>
  <% end %>

  <div class="application-form">
    <li class="col-lg-4 col-md-6 col-xs-12 create-application hidden">
      <div class="controls">
        <a href="#" class="accept"><span class="bos bos-accept"></span></a>
        <a href="#" class="cancel"><span class="bos bos-cancel"></span></a>
      </div>
      <a class="item-box">
        <%= simple_form_for :application do |f| %>
          <h3><%= f.input_field :name, label: false, class: %W[no-border], placeholder: "Name your App" %></h3>
        <% end %>
      </a>
    </li>

    <li class="col-lg-4 col-md-6 col-xs-12 add-application">
      <a class="item-box add">
        <div>+</div>
      </a>
    </li>
  </div>
</ul>

<%= prompt_modal(t('applications.modal.title'), t('applications.modal.body')) %>