config/routes.rb
###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree. 
###

require_relative '../lib/app_status'

BeaconControl::Application.routes.draw do
  mount(
    AppStatus::Rack.new do |config|
      config.add_class AppStatus::DatabaseCheckRequest, name: :database_ok?
      config.add_class AppStatus::MigrationsCheckRequest, name: :migrations_ok?
    end => '/status'
  )

  require 'sidekiq/web'
  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :applications, except: [:show] do
    member do
      post :set_apns_sandbox_cert
      post :set_apns_production_cert
    end

    resources :activities, except: [:new] do
      collection do
        get '/:event_type/new', to: 'activities#new', as: :new
        delete :destroy
      end
    end
    resources :rpush_apps_application, only: [:destroy]
    resource :applications_zones
    resource :applications_beacons

    resources :extensions, only: [:index], id: /[A-Z0-9\.]+/i, path: 'add_ons' do
      member do
        put :activate
        put :deactivate
      end
    end
  end

  devise_for :admins, controllers: {
    registrations: 'admin/registrations',
    confirmations: 'admin/confirmations',
    passwords: 'admin/passwords',
    sessions: 'admin/sessions',
  }
  as :admin do
    put 'admins/confirmation' => 'admin/confirmations#update', as: 'update_admin_confirmation'
    unless AppConfig.registerable
      get 'admins/edit' => 'admin/registrations#edit', as: :edit_admin_registration
      put 'admins/update' => 'admin/registrations#update', as: :admin_registration
    end
  end

  resource :profile, only: [:update]

  resources :admins, except: [:show], path: 'users' do
    collection do
      delete :batch_delete
    end
  end if AppConfig.user_management

  resource :static_pages, path: '', only: [] do
    member do
      get :introduction, path: 'walkthrough/intro'
      get :add_beacon, path: 'walkthrough/add_beacon'
      get :link_beacon, path: 'walkthrough/link_beacon'
      get :create_action, path: 'walkthrough/create_action'
      get :customize_features, path: 'walkthrough/customize_features'
      get :glossary, path: 'walkthrough/glossary'
    end
  end

  resources :beacons, except: [:show] do
    collection do
      patch :batch_update
      delete :batch_delete
      get :search
    end
  end
  resources :beacons_search, only: [:index]
  resources :zones

  resource :map

  resources :extension_assignments, only: [:show, :edit, :update]

  resources :extensions_marketplace, only: [:index, :edit, :update], id: /[A-Z0-9\.]+/i, path: 'add_ons' do
    member do
      put :activate
      put :deactivate
    end
  end

  scope 'api/v1', scope: 'api' do
    use_doorkeeper do
      skip_controllers :applications, :authorized_applications
    end
  end

  namespace :api do
    namespace :v1 do
      resources :configurations, only: [:index]
      resources :events, only: [:create]
    end
  end

  scope 's2s_api/v1', scope: 's2s_api' do
    use_doorkeeper do
      skip_controllers :applications, :authorized_applications
    end
  end

  namespace :s2s_api do
    namespace :v1 do
      resource :registrations, only: [:create], path: 'admins'
      resources :vendors, only: :index

      resource :password, only: [:create, :update]

      resources :applications, only: [:index, :create, :update, :destroy] do
        resources :application_settings, only: [:index] do
          collection do
            put :update
          end
        end

        resources :extensions, only: [], id: /[A-Z0-9\.]+/i do
          member do
            put :activate
            put :deactivate
          end
        end

        resources :activities, only: [:index, :create, :update, :destroy]
      end

      resources :zone_colors, only: [:index]
      resources :zones, only: [:index, :create, :update, :destroy] do
        member do
          get :beacons
        end
      end

      resources :beacons, only: [:index, :create, :update, :destroy] do
        collection do
          delete :index, action: :batch_destroy
        end

        member do
          get :info

          match 'config' => 'beacon_configs#update', via: :put
          match 'config' => 'beacon_configs#show', via: :get
          match 'beacon_updated' => 'beacon_configs#confirm', via: :put
          put :sync
        end
      end

      scope :admin do
        resources :admins, path: 'users', only: [:index, :create, :update, :destroy] if AppConfig.user_management
      end
    end
  end

  namespace :mobile do
    resources :coupons, only: [:show] do
      get :barcode
    end
  end

  if AppConfig.landing_page_url
    unauthenticated do
      as :admin do
        root to: redirect(AppConfig.landing_page_url), as: :unauthenticated_root
      end
    end
  end

  root to: 'dashboard#index'
end

app/controllers/maps_controller.rb
###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree. 
###

class MapsController < ApplicationController
  before_filter :authenticate_admin!

  def show
    @form = BeaconFilterForm.new(current_admin.account, current_ability)
  end
end

app/views/maps/show.html.erb
<%###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree. 
###%>

<% content_for :header_breadcrumbs do %>
  <span><%= t('.title') %></span>
<% end %>

<div class="map-view">
  <%= simple_form_for :beacon, url: search_beacons_path, html: { id: 'beacon-filter-form' }, defaults: { input_html: { class: %W[beacon-filter] } } do |f| %>
    <div class="row">
      <div class="col-xs-5 col-sm-3 col-md-2 col-lg-2">
        <%= button_link :add_beacon, new_beacon_path, class: %w[btn-success btn-action-save] %>
      </div>
      <div class="col-xs-7 col-sm-6 col-md-6 col-lg-4">
        <div id="beacon-actions" class="row">
          <div class="col-xs-6" id="set-zone">
            <select name="beacon[set_zone]" id="beacon_set_zone" class="select form-control selectpicker show-tick" data-live-search="true" data-size="6">
              <% @form.zones.each do |zone| %>
                <option value="<%= zone.id %>" class="with-border" data-color="<%= zone.hex_color %>" style="border-color: <%= zone.hex_color %>;"><%= truncate(zone.name, length: 30) %></option>
              <% end %>
            </select>
          </div>
          <div class="col-xs-6">
            <%= f.input :set_floor, as: :select, collection: BeaconDecorator.floors_for_select(t('.unassigned_floor'), true), prompt: false, label: false, input_html: { class: %W[selectpicker] } %>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-8 col-xs-12 pull-right">
        <div class="has-feedback">
          <%= f.input :name, label: false, placeholder: t(".search") %>
          <i class="glyphicon glyphicon-search form-control-feedback"></i>
        </div>
      </div>
    </div>
    <div class="row map-view-top-container">
      <div class="map-view-container">
        <div class="map-view-sidebar">
          <h5><%= t('.select_floor') %></h5>
          <div class="map-view-sidebar-section without-border">
            <%= f.input :floor, as: :select, collection: @form.floors, include_blank: false, label: false, input_html: { class: %W[selectpicker] } %>
          </div>

          <h5><%= t('.filter_zone') %></h5>
          <div class="map-view-sidebar-section">
            <div class="zones-list">
              <% @form.zones.each do |zone| %>
                <div class="row">
                  <div class="col-sm-12">
                    <label class="zone-choose-label">
                      <%= content_tag :span, class: %W(zone-mark), style: %W(border-color: #{zone.hex_color}) do %>
                        <%= truncate(zone.name, length: 13) %>
                      <% end %>
                      <%= check_box_tag 'beacon[zone_id][]', zone.id || 'null', checked: true %>
                    </label>
                  </div>
                </div>
              <% end %>
            </div>
          </div>

          <div class="beacon-info">
          </div>
        </div>
        <div id="beacons-map">
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= prompt_modal(t('maps.modal.title'), t('maps.modal.body')) %>