config/routes.rb
###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree. 
###

require_relative '../lib/app_status'

BeaconControl::Application.routes.draw do
  mount(
    AppStatus::Rack.new do |config|
      config.add_class AppStatus::DatabaseCheckRequest, name: :database_ok?
      config.add_class AppStatus::MigrationsCheckRequest, name: :migrations_ok?
    end => '/status'
  )

  require 'sidekiq/web'
  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :applications, except: [:show] do
    member do
      post :set_apns_sandbox_cert
      post :set_apns_production_cert
    end

    resources :activities, except: [:new] do
      collection do
        get '/:event_type/new', to: 'activities#new', as: :new
        delete :destroy
      end
    end
    resources :rpush_apps_application, only: [:destroy]
    resource :applications_zones
    resource :applications_beacons

    resources :extensions, only: [:index], id: /[A-Z0-9\.]+/i, path: 'add_ons' do
      member do
        put :activate
        put :deactivate
      end
    end
  end

  devise_for :admins, controllers: {
    registrations: 'admin/registrations',
    confirmations: 'admin/confirmations',
    passwords: 'admin/passwords',
    sessions: 'admin/sessions',
  }
  as :admin do
    put 'admins/confirmation' => 'admin/confirmations#update', as: 'update_admin_confirmation'
    unless AppConfig.registerable
      get 'admins/edit' => 'admin/registrations#edit', as: :edit_admin_registration
      put 'admins/update' => 'admin/registrations#update', as: :admin_registration
    end
  end

  resource :profile, only: [:update]

  resources :admins, except: [:show], path: 'users' do
    collection do
      delete :batch_delete
    end
  end if AppConfig.user_management

  resource :static_pages, path: '', only: [] do
    member do
      get :introduction, path: 'walkthrough/intro'
      get :add_beacon, path: 'walkthrough/add_beacon'
      get :link_beacon, path: 'walkthrough/link_beacon'
      get :create_action, path: 'walkthrough/create_action'
      get :customize_features, path: 'walkthrough/customize_features'
      get :glossary, path: 'walkthrough/glossary'
    end
  end

  resources :beacons, except: [:show] do
    collection do
      patch :batch_update
      delete :batch_delete
      get :search
    end
  end
  resources :beacons_search, only: [:index]
  resources :zones

  resource :map

  resources :extension_assignments, only: [:show, :edit, :update]

  resources :extensions_marketplace, only: [:index, :edit, :update], id: /[A-Z0-9\.]+/i, path: 'add_ons' do
    member do
      put :activate
      put :deactivate
    end
  end

  scope 'api/v1', scope: 'api' do
    use_doorkeeper do
      skip_controllers :applications, :authorized_applications
    end
  end

  namespace :api do
    namespace :v1 do
      resources :configurations, only: [:index]
      resources :events, only: [:create]
    end
  end

  scope 's2s_api/v1', scope: 's2s_api' do
    use_doorkeeper do
      skip_controllers :applications, :authorized_applications
    end
  end

  namespace :s2s_api do
    namespace :v1 do
      resource :registrations, only: [:create], path: 'admins'
      resources :vendors, only: :index

      resource :password, only: [:create, :update]

      resources :applications, only: [:index, :create, :update, :destroy] do
        resources :application_settings, only: [:index] do
          collection do
            put :update
          end
        end

        resources :extensions, only: [], id: /[A-Z0-9\.]+/i do
          member do
            put :activate
            put :deactivate
          end
        end

        resources :activities, only: [:index, :create, :update, :destroy]
      end

      resources :zone_colors, only: [:index]
      resources :zones, only: [:index, :create, :update, :destroy] do
        member do
          get :beacons
        end
      end

      resources :beacons, only: [:index, :create, :update, :destroy] do
        collection do
          delete :index, action: :batch_destroy
        end

        member do
          get :info

          match 'config' => 'beacon_configs#update', via: :put
          match 'config' => 'beacon_configs#show', via: :get
          match 'beacon_updated' => 'beacon_configs#confirm', via: :put
          put :sync
        end
      end

      scope :admin do
        resources :admins, path: 'users', only: [:index, :create, :update, :destroy] if AppConfig.user_management
      end
    end
  end

  namespace :mobile do
    resources :coupons, only: [:show] do
      get :barcode
    end
  end

  if AppConfig.landing_page_url
    unauthenticated do
      as :admin do
        root to: redirect(AppConfig.landing_page_url), as: :unauthenticated_root
      end
    end
  end

  root to: 'dashboard#index'
end

app/models/beacon/config_object.rb
require 'beacon' unless defined? Beacon

class Beacon
  class ConfigObject < OpenStruct
    attr_reader :beacon
    include AsyncValue

    # @param [Beacon] beacon
    # @param [Hash] hash
    def initialize(beacon, hash)
      super(extension_compatibility(hash.with_indifferent_access).to_hash)
      @beacon = beacon
    end

    # @param [Hash] hash
    def extension_compatibility(hash)
      hash.each_pair do |key, val|
        hash[key] = ::Beacon::ConfigObject.new(nil, val) if val.is_a?(::Hash)
      end
      hash
    end

    def attributes
      @table.to_hash
    end

    def has_own_key?(key)
      @table.key?(key.to_s.to_sym)
    end
  end
end

app/models/beacon/factory.rb
###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree. 
###

class Beacon

  #
  # Factory for Beacon model.
  #
  class Factory
    PARAMS_ORDER = %w[ vendor protocol vendor_uid proximity uuid major minor namespace instance url name ]

    NullObject = Naught.build

    # @param [Admin] admin
    # @param [Hash] params
    # @param [Application|NullObject] activity
    def initialize(admin, params, activity = NullObject.new)
      @admin = admin
      @beacon = admin.account.beacons.new(self.class.sorted_params(params))
      beacon.test_activity = activity
    end

    # @return [Beacon]
    def build
      @beacon.manager = @admin if @admin.beacon_manager?
      add_to_test_application

      @beacon
    end

    def create
      build.tap do |beacon|
        if beacon.valid?
          beacon.save
          beacon.test_activity.save
        end
      end
    end

    private

    attr_accessor :beacon, :admin

    def add_to_test_application
      return unless @admin.test_application
      @beacon.applications_beacons.new(application_id: @admin.test_application.id)
      @beacon.assign_test_activity(@beacon.test_activity)
    end

    def self.sorted_params(params)
      (params || {}).sort do |(a,_), (b,_)|
        a, b = a.to_s, b.to_s
        if PARAMS_ORDER.include?(a) && PARAMS_ORDER.include?(b)
          PARAMS_ORDER.index(a) - PARAMS_ORDER.index(b)
        elsif PARAMS_ORDER.include?(a)
          -PARAMS_ORDER.index(a)
        elsif PARAMS_ORDER.include?(b)
          PARAMS_ORDER.index(b)
        else
          a <=> b
        end
      end.reduce({}) do |memo, (k, v)|
        if k == 'proximity'
          memo['uuid'] = v
        else
          memo[k] = v
        end
        memo
      end.with_indifferent_access
    end
  end
end

app/controllers/beacons_controller.rb
###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree. 
###

class BeaconsController < AdminController
  inherit_resources
  load_and_authorize_resource
  custom_actions collection: :batch_update
  before_action :load_and_authorize_zones
  before_action :build_test_activity, only: [:new, :create, :edit, :update]
  before_action :load_config, only: [:new, :create, :edit, :update]

  has_scope :sorted, using: [:column, :direction], type: :hash, default: {
                     column: 'zones.name',
                     direction: 'asc'
                   }
  has_scope :with_beacon_or_zone_name, as: :beacon_name

  include BeaconAllowedParams # MUST be after inherit_resources and load_and_authorize_resource

  def new
    resource.uuid ||= current_admin.default_beacon_uuid
    @beacon = resource.decorate
    new!
  end

  def index
    @beacons = BeaconDecorator.decorate_collection apply_scopes(collection).all
    index!
  end

  def search
    @beacons = collection.with_location.search(search_params)

    render json: @beacons,
           each_serializer: S2sApi::V1::BeaconSerializer
  end

  def create
    @beacon = create_beacon
    @beacon.persisted? ? redirect_to_beacons : render_new
  end

  def update
    resource.update_test_activity(activity_permitted_params)
    resource.beacon_config.update_data(current_admin, config_params)

    update! do |format|
      format.json { render json: S2sApi::V1::BeaconSerializer.new(resource) }
      format.html { redirect_to_beacons } if resource.errors.empty?
    end
  end

  def destroy
    destroy! do |format|
      format.json { render json: {}, status: :ok }
      format.html { redirect_to beacons_url }
    end
  end

  def batch_update
    collection.where(id: params[:beacon_ids]).
      reorder('').
      update_all(permitted_params[:beacon])
    redirect_to beacons_url
  end

  def batch_delete
    collection.destroy_all(id: params[:beacon_ids])
    redirect_to beacons_url
  end

  private

  def redirect_to_beacons
    redirect_to beacons_url
  end

  def render_new
    render :new
  end

  def create_beacon
    Beacon::Factory.new(
      current_admin,
      permitted_params[:beacon],
      Activity.new(activity_permitted_params)
    ).create
  end

  def begin_of_association_chain
    current_admin.account
  end

  def end_of_association_chain
    super.includes(:zone).references(:zone)
  end

  def load_and_authorize_zones
    @zones = Zone.accessible_by(current_ability)
  end

  def build_test_activity
    resource.build_test_activity
  end

  def load_config
    c = resource.beacon_config || resource.build_beacon_config
    c.load_data(current_admin)
  end
end

app/controllers/s2s_api/v1/beacons_controller.rb
###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree.
###

module S2sApi
  module V1
    class BeaconsController < BaseController
      inherit_resources
      load_and_authorize_resource
      before_action :build_test_activity,
                    only: [:create, :update]
      before_action :load_config, only: [:new, :create, :edit, :update]

      include BeaconAllowedParams # MUST be after inherit_resources and load_and_authorize_resource
      self.responder = S2sApiResponder

      rescue_from ::ActionController::ParameterMissing do |error|
        render json: { error: error.message }, status: 422
      end

      rescue_from ::KontaktIo::Error::NotFound do |error|
        render json: { error: error.message }, status: 422
      end

      actions :index, :update, :destroy

      def index
        beacons = end_of_association_chain
        respond_with(beacons, controller: self)
      end

      def info
        wrapped = case resource.vendor
                  when 'Kontakt' then KontaktIoBeacon.new(resource, current_admin)
                  else WrappedBeacon.new(resource, current_admin)
                  end
        respond_with(wrapped)
      end

      def create
        activity = Activity.new(activity_permitted_params)
        resource = Beacon::Factory.new(
          current_admin,
          permitted_params[:beacon],
          activity
        ).create

        respond_with(resource)
      end

      def update
        resource.update_test_activity(activity_permitted_params)
        resource.beacon_config.update_data(current_admin, config_params)
        update!
      end

      def sync
        render json: resource,
               serializer: ::S2sApi::V1::BeaconSerializer
      end

      def batch_destroy
        @beacons = collection.where(id: params[:ids])
        @beacons.delete_all

        respond_with(@beacons)
      end

      private

      def begin_of_association_chain
        current_admin.account
      end

      def end_of_association_chain
        super.includes(:beacon_config).search(search_params)
      end

      def default_serializer_options
        { root: collection_action? ? :ranges : :range }
      end

      def build_test_activity
        resource.build_test_activity
      end

      def load_config
        c = resource.beacon_config || resource.build_beacon_config
        c.load_data(current_admin)
      end
    end
  end
end

app/helpers/beacons_helper.rb
module BeaconsHelper

  # @param [Array<Zone>] coll
  # @return [Array]
  def select_zone_collection_from(coll)
    coll.map do |zone|
      [
        truncate(zone.name, length: 40),
        zone.id,
        {
          class: %W[with-border],
          style: %W(border-color: #{zone.hex_color}),
          data: {
            group: zone.manager_id.to_s,
            color: zone.hex_color
          }
        }
      ]
    end
  end

  def vendor_beacon(beacon, admin=current_admin)
    case beacon.vendor
    when 'Kontakt' then KontaktIoBeacon.new(beacon, admin)
    else WrappedBeacon.new(beacon, admin)
    end
  end

  def live_search_value(obj, *fields)
    fields.map do |field|
      obj.send(field).to_s
    end.join(' | ')
  end

  def master_beacon(beacon)
    return nil unless beacon && beacon.vendor == 'Kontakt'
    master = beacon.config && beacon.config.status && beacon.config.status.master
    if master
      Beacon.kontakt_io.merge(KontaktIoMapping.with_uid(master)).last
    else
      nil
    end
  end

  def master_beacon?(beacon)
    return false unless beacon
    return false unless beacon.persisted?
    !master_beacon(beacon).nil?
  end
end

app/views/beacons/form/_basic.erb
<div class="row form-container">
  <div class="col-md-6 first-column">
    <div class="control-group">
      <div class="controls">

        <%= f.input :name,
                    input_html: {
                        data: {
                            required: true
                        }
                    }
        %>
      </div>
    </div>

    <div class="control-group" style="<%= 'display:none;' if @beacon.imported? %>">
      <div class="controls">
        <%= f.input :vendor,
                    as: :select,
                    collection: Beacon::VENDORS,
                    include_blank: false,
                    input_html: {
                        readonly: @beacon.imported?,
                        class: %W[selectpicker event-publisher],
                        data: {
                            live_search: true
                        }
                    }
        %>
      </div>
    </div>

    <div class="control-group event-subscriber" data-publisher="#beacon_vendor" data-match="Kontakt" data-action="show">
      <div class="controls">

        <%= f.input :vendor_uid,
                    label: render('beacons/form/vendor_uid_tooltip'),
                    input_html: {
                        data: {
                            :'validate-if' => '#beacon_vendor=Kontakt',
                            pattern: '^[\w\d]{4,5}$',
                            required: true
                        },
                        value: beacon.try(:vendor_uid)
                    }
        %>
      </div>
    </div>

    <% unless @beacon.imported? %>
      <div class="control-group event-subscriber with-huge-space" data-publisher="#beacon_vendor" data-match="Kontakt" data-action="show">
        <div class="controls">
          <span class="text-muted">
            <%= t('beacons.form.active_kontakt_io_addon') %>
            <%= link_to t('beacons.form.kontakt_io_addon'),
                        activate_extensions_marketplace_path('Kontakt.io'),
                        method: :put
            %>
          </span>
        </div>
      </div>
    <% end %>

    <%= render 'beacons/form/state',
               f: f,
               beacon: beacon
    %>

    <%- if master_beacon(@beacon) %>
      <div id="beacon-cloud" class="with-huge-space control-group">
        <div class="controls">
          <div class="form-group">
            <label class="control-label">
              <%= t('beacons.form.synchronized_by') %>
            </label>
            <%= link_to edit_beacon_path(master_beacon(@beacon)) do %>
              <div class="form-control">
                <%= master_beacon(@beacon).name %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

    <% if @beacon.persisted? && @beacon.triggers.joins(:application).any? %>
      <div id="beacon-applications" class="with-huge-space control-group">
        <div class="controls">
          <div class="form-group">
            <label class="control-label">
              <%= t('beacons.form.connected_applications') %>
            </label>
            <%- @beacon.triggers.joins(:application).each do |trigger| %>
              <% if trigger.application %>
                <%= link_to application_activities_path(trigger.application) do %>
                  <div class="form-control">
                    <div class="col-xs-8">
                      <span class="small-app-icon"></span>
                      <%= trigger.application.name %>
                    </div>
                    <div class="col-xs-4 text-right actions">
                      <% if trigger.application.activities.count == 0 %>
                        <%= t('beacons.form.no_actions') %>
                      <% else %>
                        <%= trigger.application.activities.count %>
                        <%= t('beacons.form.action').downcase.pluralize(trigger.application.activities.count) %>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <%- end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-md-6 second-column">
    <%= render 'beacons/form/map',
               f: f,
               zones: zones
    %>
  </div>
</div>

app/views/beacons/form/_map.erb
<div class="">
  <!-- GOOGLE MAP -->
  <div id="beacon-map" style="height:192px;"></div>
  <!-- /GOOGLE MAP -->
  <div class="control-group">
    <div class="controls">
      <div class="row">
        <div class="col-sm-6">
          <%= f.input :floor,
                      as: :select,
                      collection: BeaconDecorator.floors_for_select(t('beacons.form.unassigned_floor'), true),
                      include_blank: false,
                      input_html: {
                          class: %W[selectpicker show-tick],
                          data: {
                              live_search: true
                          }
                      }
          %>
        </div>
        <%= render 'beacons/form/zone_field', f: f, zones: zones %>
      </div>
    </div>
  </div>
  <div class="control-group">
    <div class="location">
      <%= f.input :location %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <div class="row">
        <div class="col-md-6">
          <%= f.input :lat, as: :string %>
        </div>
        <div class="col-md-6">
          <%= f.input :lng, as: :string %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/beacons/form/_settings.erb
<div class="row form-container">
  <div class="col-md-6 first-column">

    <div class="control-group">
      <div class="controls">
        <%= f.input :protocol,
                    collection: Beacon::PROTOCOLS,
                    as: :select,
                    disabled: 'Eddystone',
                    include_blank: false,
                    input_html: {
                        class: %W[selectpicker event-publisher],
                        data: {
                            live_search: false
                        }
                    }
        %>
      </div>
    </div>

    <div class="event-subscriber control-group" data-publisher="#beacon_protocol" data-action="show" data-on="change" data-match="iBeacon">
      <div class="row">
        <div class="col-xs-12">
          <div class="controls">
            <%= f.input :uuid,
                        as: :old_value_tooltip,
                        beacon: beacon,
                        input_html: {
                            class: %w[uuid-input],
                            data: {
                                :'validate-if' => '#beacon_protocol=iBeacon',
                                required: true,
                                pattern: Beacon::UuidFormat::REGEX.inspect.gsub(/\//, '')
                            }
                        }
            %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="controls">
          <div class="col-xs-6">
            <%= f.input :major,
                        as: :old_value_tooltip,
                        input_html: {
                            data: {
                                :'validate-if' => '#beacon_protocol=iBeacon',
                                required: true,
                                pattern: '\d+'
                            }
                        }
            %>
          </div>
          <div class="col-xs-6">
            <%= f.input :minor,
                        as: :old_value_tooltip,
                        input_html: {
                            data: {
                                :'validate-if' => '#beacon_protocol=iBeacon',
                                required: true,
                                pattern: '\d+'
                            }
                        }
            %>
          </div>
        </div>
      </div>
    </div>

    <div class="event-subscriber control-group" data-publisher="#beacon_protocol" data-action="show" data-on="change" data-match="Eddystone">
      <div class="row">
        <div class="controls">
          <div class="col-xs-6">
            <%= f.input :namespace,
                        as: :old_value_tooltip,
                        id: :namespace,
                        input_html: {
                            data: {
                                :'validate-if' => '#beacon_protocol=Eddystone',
                                required: true
                            }
                        }
            %>
          </div>
          <div class="col-xs-6">
            <%= f.input :instance,
                        as: :old_value_tooltip,
                        id: :instance,
                        input_html: {
                            data: {
                                :'validate-if' => '#beacon_protocol=Eddystone',
                                required: true
                            }
                        }
            %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12">
          <div class="controls">
            <%= f.input :signal_interval,
                        as: :old_value_tooltip
            %>
          </div>
        </div>
      </div>
    </div>

    <%= render 'beacons/form/test_notification',
               f: f,
               beacon: beacon,
               custom_attributes: beacon.test_activity.custom_attributes
    %>

  </div>
  <div class="col-md-6 second-column">
    <% if @beacon.vendor == 'Kontakt' %>
      <div class="control-group" style="<%= 'display:none;' if master_beacon?(beacon) %>">
        <div class="controls" style="color:#d62c1a;margin-bottom:20px;">
          <%= t('beacons.form.missing_cloud_message') %>
        </div>
      </div>

      <%= f.fields_for(:config) do |_| %>
        <div class="control-group event-subscriber" data-publisher="#beacon_protocol" data-action="show" data-match="iBeacon">
          <div class="controls">
            <%= f.input :signal_interval,
                        as: :old_value_tooltip
            %>
          </div>
        </div>

        <div class="control-group">
          <div class="controls relative">
            <div class="transmission-power-value"><span>1</span>/7</div>
            <%= f.input :transmission_power,
                        as: :old_value_tooltip,
                        id: :"transmission_power-slider",
                        input_html: {
                            id: :transmission_power,
                            style: 'display:block;width:100%',
                            class: %w[slider],
                            data: {
                                slider_min:     0,
                                slider_max:     7,
                                slider_step:    1,
                                slider_value:   beacon.transmission_power,
                                slider_handle:  :square
                            }
                        }
            %>
          </div>
        </div>
      <%- end %>
    <% end %>
  </div>
</div>

app/views/beacons/form/_state.erb
<% if @beacon.persisted? %>
  <div id="beacon-state-data" class="with-huge-space form-control control-group beacon-state">
    <div id="beacon-working-status" class="row">
      <div class="col-xs-12">
        <%= t('beacons.form.working_status') %>:
        <strong><%= t("beacons.form.beacon_#{1 ? 'active' : 'inactive'}") %></strong>
      </div>
    </div>
    <div id="beacon-device-id" class="row">
      <div class="col-xs-12">
        <%= t('beacons.form.device_id') %>:
        <strong><%= beacon.config.unique_id || "Unknown" %></strong>
      </div>
    </div>
    <div id="beacon-device-type" class="row">
      <div class="col-xs-12">
        <%= t('beacons.form.vendor') %>:
        <span class="event-publisher" data-init="true">
          <strong><%= beacon.vendor %></strong>
        </span>
      </div>
    </div>
    <div id="beacon-firmware" class="row">
      <div class="col-xs-12">
        <%= t('beacons.form.firmware') %>:
        <strong>
          <% if beacon.config.firmware.present? %>
            <%- if beacon.config.latest_firmware %>
              <%= beacon.config.firmware %>
            <%- else %>
              <span style="color:darkred">
                <%= beacon.config.firmware %>!
              </span>
            <%- end %>
          <% else %>
            <%= t('beacons.form.battery_unknown') %>
          <% end %>
        </strong>
      </div>
    </div>
    <div id="beacon-battery" class="row">
      <div class="col-xs-12">
        <%= t('beacons.form.battery') %>:
        <strong>
          <%- if beacon.config.battery_level.nil? %>
            <%= t('beacons.form.battery_unknown') %>
          <%- else %>
            <%= beacon.config.battery_level %>%
          <%- end %>
        </strong>
      </div>
    </div>
    <div id="beacon-last-action" class="row">
      <div class="col-xs-12">
        <%= t('beacons.form.last_action') %>:
        <strong><%= Time.at(beacon.config.last_event_timestamp.to_i).strftime('%d.%m.%Y %H:%M') %></strong>
      </div>
    </div>
    <div id="beacon-average-connection-interval" class="row">
      <div class="col-xs-12">
        <%= t('beacons.form.average_connection_interval') %>s:
        <strong>
          <% if beacon.config.avg_event_interval.present? %>
            <%= beacon.config.avg_event_interval %>s
          <% else %>
            <%= t('beacons.form.battery_unknown') %>
          <% end %>
        </strong>
      </div>
    </div>
  </div>
<% end %>

app/views/beacons/form/_test_notification.html.erb
<%###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree. 
###%>

<div class="well control-group test-notification-group with-huge-space">
  <%= f.simple_fields_for beacon.test_activity do |activity_form| %>

    <%= activity_form.simple_fields_for :trigger do |trigger_form| %>
      <%= trigger_form.label :test, class: %W[trigger-test] do %>
        <%= trigger_form.input :test,
                               label: false,
                               inline_label: "#{t('beacons.test_notification.title')} <span class=\"grayed\">#{t('beacons.test_notification.hint', mobile_app_url: "https://itunes.apple.com/pl/app/beaconctrl/id1020666394?mt=8")}</span>".html_safe,
                               input_html: {
                                   class: %w[event-publisher]
                               }
        %>
      <% end %>
    <% end %>

    <div class="event-subscriber margin-t15" data-publisher="#beacon_activity_trigger_attributes_test" data-action="show" data-match="true">
      <%= activity_form.simple_fields_for :trigger do |trigger_form| %>

        <%= activity_form.simple_fields_for(:custom_attributes, custom_attributes.blank? ? CustomAttribute.new : custom_attributes) do |ff| %>
          <%= activity_form.input :name,
                                  label: t('beacons.test_notification.name'),
                                  placeholder: t('beacons.test_notification.placeholder'),
                                  input_html: {
                                      class: %W[col-xs-6],
                                      value: activity_form.object.name.present? ? activity_form.object.name : t('beacons.test_notification.placeholder')
                                  }
          %>

          <%= ff.hidden_field :name, value: "text" %>
          <%= ff.input :value,
                       label: 'Message',
                       input_html: {
                           value: ff.object.value.present? ? ff.object.value : t('beacons.test_notification.default_message'),
                           placeholder: t('beacons.test_notification.default_message')
                       }
          %>

          <div class="form-break-line"></div>

          <%= trigger_form.input :event_type,
                                 collection: Trigger::Collection.list(current_admin.test_application, 'BeaconTrigger'),
                                 value_method: :type,
                                 include_blank: false,
                                 input_html: {
                                     class: %W[selectpicker col-xs-6]
                                 }
          %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/beacons/form/_vendor_uid_tooltip.html.erb
<%= t('beacons.form.device_id') %>
<div class="tooltip-button-wrapper">
  <div class="bos bos-info_dark tooltip-button" data-toggle="tooltip" data-placement="top" title="<%= t('beacons.form.device_id_tooltip') %>"></div>
</div>

app/views/beacons/form/_zone_field.erb
<%= content_tag :div, class: %W[col-sm-6], style: %W(border-color: #{current_beacon_zone_color}) do %>
  <%= f.association :zone,
                    as: :select,
                    include_blank: false,
                    input_html: {
                        class: %W[selectpicker show-tick select-with-border],
                        data: {
                            live_search: true
                        }
                    },
                    collection: select_zone_collection_from([BeaconFilterForm::UNASSIGNED_ZONE,*zones])
  %>
<% end %>